Repository Sven65/Action-Test, pull requests merged in 2019-11, with the labels that each got.

#1 Create test
  test
Labels: bug

#2 Update test
  test
Labels: bug

#3 Update test
  test
Labels: bug

#4 Update test
  test
Labels: bug

#5 Update test
  test
Labels: bug

#6 Update test
  test
Labels: bug

#7 Update test
  test
Labels: bug

#8 Update test
  test
Labels: bug

#9 Update test
  test
Labels: bug

#10 Update test
  test
Labels: bug

#11 Update test
  test
Labels: bug, documentation

#12 Update test
  test
Labels: bug, documentation

#13 fine
  test
Labels: bug, documentation, duplicate, enhancement

#14 Update test
  test
Labels: bug, documentation, duplicate
